export const cardArray = [
    {
        id: 0,
        title: 'Пвх материал 1й сорт',
        price: '160 ₽',
        adress: 'Казань, р-н Вахитовский',
        date: '15 июля 11:39',
        img: '/images/productImage.png',
        description: 'Продаю не спеша самокат в хорошем состоянии.',
    },
    {
        id: 1,
        title: 'Пвх материал 2й сорт',
        price: '170 ₽',
        adress: 'Казань, р-н Вахитовский',
        date: '10 июня 16:51',
        img: '/images/productImage.png',
        description: 'Продаю не спеша самокат в хорошем состоянии.',
    },
    {
        id: 2,
        title: 'Пвх материал 3й сорт',
        price: '180 ₽',
        adress: 'Казань, р-н Вахитовский',
        date: '29 июля 09:11',
        img: '/images/productImage.png',
        description: 'Продаю не спеша самокат в хорошем состоянии.',
    },
    {
        id: 3,
        title: 'Пвх материал 4й сорт',
        price: '190 ₽',
        adress: 'Казань, р-н Вахитовский',
        date: '30 июня 11:22',
        img: '/images/productImage.png',
        description: 'Продаю не спеша самокат в хорошем состоянии.',
    },
    {
        id: 4,
        title: 'Пвх материал 5й сорт',
        price: '200 ₽',
        adress: 'Казань, р-н Вахитовский',
        date: '24 июля 18:39',
        img: '/images/productImage.png',
        description: 'Продаю не спеша самокат в хорошем состоянии.',
    },
    {
        id: 5,
        title: 'Пвх материал 6й сорт',
        price: '210 ₽',
        adress: 'Казань, р-н Вахитовский',
        date: '1 июля 08:52',
        img: '/images/productImage.png',
        description: 'Продаю не спеша самокат в хорошем состоянии.',
    },

];